const INCREASE_COUNT = "INCREASE_COUNT";
const DECREASE_COUNT = "DECREASE_COUNT";
const SAVE_SELECT_VALUE = "SAVE_SELECT_VALUE";
const RESET_COUNT = "RESET_COUNT";
const LOADING = "LOADING";
const API_CALL_SUCCESS = "API_CALL_SUCCESS";
const ERROR = "ERROR";
const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";
const REMOVE_SELECTED_TASKS_SUCCESS = "REMOVE_SELECTED_TASKS_SUCCESS";
const SAVE_EDITED_TASK_SUCCESS = "SAVE_EDITED_TASK_SUCCESS";

export {
  INCREASE_COUNT,
  DECREASE_COUNT,
  SAVE_SELECT_VALUE,
  RESET_COUNT,
  LOADING,
  API_CALL_SUCCESS,
  ERROR,
  ADD_TASK_SUCCESS,
  REMOVE_TASK_SUCCESS,
  REMOVE_SELECTED_TASKS_SUCCESS,
  SAVE_EDITED_TASK_SUCCESS,
};
