const INCREASE_COUNT = "INCREASE_COUNT";
const DECREASE_COUNT = "DECREASE_COUNT";
const SAVE_SELECT_VALUE = "SAVE_SELECT_VALUE";
const RESET_COUNT = "RESET_COUNT";

export { INCREASE_COUNT, DECREASE_COUNT, SAVE_SELECT_VALUE, RESET_COUNT };
