const LOADING = "LOADING";
const ERROR = "ERROR";

const API_CALL_SUCCESS = "API_CALL_SUCCESS";
const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";
const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";
const SAVE_EDITED_TASK_SUCCESS = "SAVE_EDITED_TASK_SUCCESS";
const REMOVE_SELECTED_TASKS_SUCCESS = "REMOVE_SELECTED_TASKS_SUCCESS";
const CHANGE_TASK_STATUS_SUCCESS = "CHANGE_TASK_STATUS_SUCCESS";

export {
  LOADING,
  ERROR,
  API_CALL_SUCCESS,
  ADD_TASK_SUCCESS,
  REMOVE_TASK_SUCCESS,
  REMOVE_SELECTED_TASKS_SUCCESS,
  SAVE_EDITED_TASK_SUCCESS,
  GET_SINGLE_TASK_SUCCESS,
  CHANGE_TASK_STATUS_SUCCESS,
};
